const languages = {
    af: "Afrikaans",
    sq: "Albania",
    am: "Amharik",
    ar: "Arab",
    hy: "Armenia",
    az: "Azerbaijan",
    eu: "Basque",
    be: "Belarusia",
    bn: "Bengali",
    bs: "Bosnia",
    bg: "Bulgaria",
    ca: "Katala",
    ceb: "Cebuano",
    ny: "Chichewa",
    "zh-CN": "Tionghoa (Sederhana)",
    "zh-TW": "Tionghoa (Tradisional)",
    co: "Korsika",
    hr: "Kroasia",
    cs: "Cheska",
    da: "Denmark",
    nl: "Belanda",
    en: "Inggris",
    eo: "Esperanto",
    et: "Estonia",
    tl: "Filipino",
    fi: "Finlandia",
    fr: "Prancis",
    fy: "Frisia",
    gl: "Galisia",
    ka: "Georgia",
    de: "Jerman",
    el: "Yunani",
    gu: "Gujarat",
    ht: "Kreol Haiti",
    ha: "Hausa",
    haw: "Hawaii",
    iw: "Ibrani",
    hi: "Hindi",
    hmn: "Hmong",
    hu: "Hungaria",
    is: "Islandia",
    ig: "Igbo",
    id: "Indonesia",
    ga: "Irlandia",
    it: "Italia",
    ja: "Jepang",
    jw: "Jawa",
    kn: "Kannada",
    kk: "Kazakh",
    km: "Khmer",
    rw: "Kinyarwanda",
    ko: "Korea",
    ku: "Kurdi (Kurmanji)",
    ky: "Kirgiz",
    lo: "Lao",
    la: "Latin",
    lv: "Latvia",
    lt: "Lituania",
    lb: "Luksemburg",
    mk: "Makedonia",
    mg: "Malagasi",
    ms: "Melayu",
    ml: "Malayalam",
    mt: "Malta",
    mi: "Maori",
    mr: "Marathi",
    mn: "Mongolia",
    my: "Myanmar (Burma)",
    ne: "Nepali",
    no: "Norwegia",
    or: "Odia (Oriya)",
    ps: "Pashto",
    fa: "Persia",
    pl: "Polski",
    pt: "Portugis",
    pa: "Punjabi",
    ro: "Rumania",
    ru: "Rusia",
    sm: "Samoa",
    gd: "Gaelik Skotlandia",
    sr: "Serbia",
    st: "Sesotho",
    sn: "Shona",
    sd: "Sindhi",
    si: "Sinhala",
    sk: "Slovak",
    sl: "Slovenia",
    so: "Somali",
    es: "Spanyol",
    su: "Sunda",
    sw: "Swahili",
    sv: "Swedia",
    tg: "Tajik",
    ta: "Tamil",
    tt: "Tatar",
    te: "Telugu",
    th: "Thai",
    tr: "Turki",
    tk: "Turkmen",
    uk: "Ukraina",
    ur: "Urdu",
    ug: "Uyghur",
    uz: "Uzbek",
    vi: "Vietnam",
    cy: "Welsh",
    xh: "Xhosa",
    yi: "Yiddish",
    yo: "Yoruba",
    zu: "Zulu",
};

export default languages;
